#! /usr/bin/env bash
#
# Installs dotfiles in the user's `HOME` directory

. "$_GO_USE_MODULES" 'copy'

_dotfiles_add_source_bash_dev() {
  local candidates=(
    '.bash_profile'
    '.bash_login'
    '.profile'
    '.bashrc'
  )
  local source_bash_dev='. "$HOME/.bash_dev"'
  local bash_startup

  for bash_startup in "${candidates[@]}"; do
    bash_startup="$HOME/$bash_startup"
    if [[ -f "$bash_startup" ]]; then
      break
    fi
  done

  if ! grep -q "$source_bash_dev" "$bash_startup"; then
    printf '%s\n' "$source_bash_dev" >>"$bash_startup"
  fi
}

_dotfiles() {
  local dotfile

  @go.log INFO Copying dotfiles into "$HOME"

  while IFS= read -r dotfile; do
    copy_file_safely "$dotfile" 'dotfiles/' "$HOME"
  done < <(find dotfiles -type f)
  _dotfiles_add_source_bash_dev
}

_dotfiles "$@"
