#! /usr/bin/env bash
#
# Installs dotfiles in the user's `HOME` directory

. "$_GO_USE_MODULES" 'copy' 'walk'

_dotfiles_add_source_bash_dev() {
  local candidates=(
    '.bash_profile'
    '.bash_login'
    '.profile'
    '.bashrc'
  )
  local source_bash_dev='. "$HOME/.bash_dev"'
  local bash_startup

  for bash_startup in "${candidates[@]}"; do
    bash_startup="$HOME/$bash_startup"
    if [[ -f "$bash_startup" ]]; then
      break
    fi
  done

  if ! grep -q "$source_bash_dev" "$bash_startup"; then
    printf '%s\n' "$source_bash_dev" >>"$bash_startup"
  fi
}

_dotfiles_copy_to_user_home_dir() {
  copy_file_safely "$1" 'dotfiles/' "$HOME"
}

_dotfiles() {
  local dotfiles
  local dotfile

  @go.log INFO Copying dotfiles into "$HOME"
  walk_dotfiles _dotfiles_copy_to_user_home_dir
  _dotfiles_add_source_bash_dev
}

_dotfiles "$@"
