#! /bin/bash
#
# Install language version managers
#
# Usage:  {{go}} {{cmd}} <app-sys-root>
#
# Globals:
#   GO_VERSION:      Version of Go to install
#   GVM_VERSION:     Tag or commit hash of gvm version to install
#   NODEJS_VERSION:  Version of Node.js to install
#   NVM_VERSION:     Tag or commit hash of nvm version to install
#   PYTHON_VERSION:  Version of Python to install
#   PYENV_VERSION:   Tag or commit hash of pyenv version to install
#   RUBY_VERSION:    Version of Ruby to install
#   RBENV_VERSION:   Tag or commit hash of rbenv version to install

_languages() {
  local language

  if [ ! -d $APPS_ROOT ]; then
    mkdir -p $APPS_ROOT
  fi

  if [ ! -d /etc/profile.d ]; then
    mkdir /etc/profile.d
    cat >>/etc/profile <<'END_PROFILE'
for script in /etc/profile.d/*.sh
do
  . $script
done
END_PROFILE
  fi

  for language in "${INSTALL_LANGUAGES[@]}"; do
    @go install languages "$language"
  done
}

_languages "$@"
