#! /bin/bash
#
# Install language version managers
#
# Usage:  {{go}} {{cmd}} <app-sys-root>
#
# Globals:
#   GO_VERSION:      Version of Go to install
#   GVM_VERSION:     Tag or commit hash of gvm version to install
#   NODEJS_VERSION:  Version of Node.js to install
#   NVM_VERSION:     Tag or commit hash of nvm version to install
#   PYTHON_VERSION:  Version of Python to install
#   PYENV_VERSION:   Tag or commit hash of pyenv version to install
#   RUBY_VERSION:    Version of Ruby to install
#   RBENV_VERSION:   Tag or commit hash of rbenv version to install

_languages() {
  local app_sys_root="$1"
  local language

  if [ ! -d $app_sys_root ]; then
    mkdir -p $app_sys_root
  fi

  if [ ! -d /etc/profile.d ]; then
    mkdir /etc/profile.d
    cat >>/etc/profile <<'END_PROFILE'
for script in /etc/profile.d/*.sh
do
  . $script
done
END_PROFILE
  fi

  @go install languages "go" "$GO_VERSION" "$GVM_VERSION"
  @go install languages "node" "$NODEJS_VERSION" "$NVM_VERSION"
  @go install languages "python" "$PYTHON_VERSION" "$PYENV_VERSION"
  @go install languages "ruby" "$RUBY_VERSION" "$RBENV_VERSION"
}

_languages "$@"
