#! /usr/bin/env bash
#
# Short description of the copy module
#
# Exports:
#   copy_file_safely
#     Copy a file, creating directories if need be, only if it doesn't exist

. "$_GO_USE_MODULES" 'walk'

# Copy a file, creating directories if need be, only if it doesn't exist
#
# Arguments:
#   src:         Path to the file to copy
#   src_prefix:  Prefix to trim from the src file when computing destination dir
#   dest_dir:    Destination directory for the copied file
#   dir_perms:   Permissions to set for created directories
#   file_perms:  Permissions to set for copied files
copy_file_safely() {
  local src="$1"
  local src_prefix="$2"
  local dest_dir="$3"
  local dir_perms="${4:-700}"
  local file_perms="${5:-600}"
  local dest="$dest_dir/${src#$src_prefix}"
  local dest_parent="${dest_dir%/*}"

  printf '%s => %s\n' "$src" "$dest"
  create_dirs_with_permissions "$dest_dir" "$dir_perms"

  if [[ ! -f "$dest" ]]; then
    if ! cp "$src" "$dest"; then
      @go.log FATAL Failed to copy "$src" to "$dest"
    elif ! chmod "$file_perms" "$dest"; then
      @go.log FATAL Failed to set permissions on "$dest"
    fi
  elif ! diff "$src" "$dest" >/dev/null; then
    @go.log WARN "$dest" exists and differs from "$src"
  fi
}
