#! /usr/bin/env bash
#
# Functions for processing lists of dev setup files
#
# Exports:
#   process_files
#     Perform an operation on each path that is a regular file
#
#   process_dotfiles
#     Perform an operation on each dotfile path
#
#   process_user_bin_scripts
#     Perform an operation on all user-bin script paths

# Perform an operation on each path that is a regular file
#
# The recursion is terminated when `operation` returns a nonzero value.
#
# Arguments:
#   operation:  Name of the function taking a file path as an argument
#   ${@:1}:     List of paths to begin examining
process_files() {
  local f
  for f in "${@:1}"; do
    if [[ -f "$f" ]] && ! "$1" "$f"; then
      return
    elif [[ -d "$f" ]]; then
      process_files "$1" "$f"/*
    fi
  done
}

# Perform an operation on each dotfile path
#
# Arguments:
#   operation:  Function taking a dotfile path as an argument
process_dotfiles() {
  process_files "$1" dotfiles/.[A-Za-z0-9_-]*
}

# Perform an operation on all user-bin script paths
#
# Arguments:
#   operation:  Function taking a user-bin script path as an argument
process_user_bin_scripts() {
  if [[ -z "$PLATFORM_ID" ]]; then
    . "$_GO_USE_MODULES" 'platform'
  fi
  process_files "$1" user-bin/{common,$PLATFORM_ID}/*
}
